{
 "title": "Ultimaker 3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bed temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature (°C)" }
   ],
   "targets": [
    {
     "alias": "Current bed temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ultimaker3",
     "select": [
      [
       { "params": [ "bed_temperature_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Target bed temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ultimaker3",
     "select": [
      [
       { "params": [ "bed_temperature_target" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Extruder temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature (°C)" }
   ],
   "targets": [
    {
     "alias": "Extruder 0 current temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ultimaker3",
     "select": [
      [
       { "params": [ "extruder_0_temperature_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Extruder 0 target temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ultimaker3",
     "select": [
      [
       { "params": [ "extruder_0_temperature_target" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Extruder 1 current temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ultimaker3",
     "select": [
      [
       { "params": [ "extruder_1_temperature_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Extruder 1 target temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ultimaker3",
     "select": [
      [
       { "params": [ "extruder_1_temperature_target" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "measurement": "ultimaker3",
     "query": "SELECT \"printer_status\" FROM \"ultimaker3\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "printer_status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Print name",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "ultimaker3",
     "select": [
      [
       { "params": [ "print_job_name" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Print progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 8 },
   "targets": [
    {
     "measurement": "ultimaker3",
     "query": "SELECT \"print_job_progress\" FROM \"ultimaker3\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "print_job_progress" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total time to print",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 8 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ultimaker3",
     "select": [
      [
       { "params": [ "print_job_time_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time to finish",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 11 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ultimaker3",
     "query": "SELECT mean(\"print_job_time_total\") - mean(\"print_job_time_elapsed\") FROM \"ultimaker3\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "print_job_time_elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "-" ], "type": "math" }
      ],
      [
       { "params": [ "print_job_time_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Printed jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "measurement": "ultimaker3",
     "query": "SELECT distinct(\"print_job_name\"), \"print_job_state\" FROM \"ultimaker3\"",
     "select": [
      [
       { "params": [ "print_job_name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  }
 ]
}